In [1]:
import os, sys

module_path = r'C:\Users\el1ja\OneDrive\Рабочий стол\программирование\AI\NLP'
sys.path.append(module_path)

from nlp_utils.pandas_tools import *

import pandas as pd

In [ ]:
df = pd.DataFrame.from_dict({'a': [1, 2, 3]})

In [2]:
import numpy as np

In [3]:
l1 = [11, 22, 33]
l2 = [55, 66, 77]

In [4]:
df[['b', 'v']] = pd.DataFrame(zip(l1, l2))
df

   a   b   v
0  1  11  55
1  2  22  66
2  3  33  77

In [5]:
df

   a   b   v
0  1  11  55
1  2  22  66
2  3  33  77

In [6]:
df[['b', 'v']] = pd.DataFrame([[1, 2], [3, 4]])
df

   a    b    v
0  1  1.0  2.0
1  2  3.0  4.0
2  3  NaN  NaN

In [8]:
df.columns.to_list()

['a', 'b', 'v']

In [9]:
df = pd.DataFrame.from_records([{'a': {'a1': [1, 2, 3], 'a2': [1, 2, 3]}, 'b': {'b1': [1, 2, 3]}}])

In [10]:
df

                                    a                  b
0  {'a1': [1, 2, 3], 'a2': [1, 2, 3]}  {'b1': [1, 2, 3]}

In [18]:
type(df['a'][0])

dict

In [ ]:
dict_column_to_columns(df, 'a', is_multiindex=False)

a_a1    object
a_a2    object
dtype: object

In [8]:
dict_columns_to_columns(df, is_multiindex=True)

           a                     b
          a1         a2         b1
0  [1, 2, 3]  [1, 2, 3]  [1, 2, 3]

In [2]:
df = pd.DataFrame.from_records([{'a': {'a1': [1, 2, 3], 'a2': [1, 2, 3]}, 'b': {'b1': [1, 2, 3]}, 'c': 4}])

In [4]:
df

                                    a                  b  c
0  {'a1': [1, 2, 3], 'a2': [1, 2, 3]}  {'b1': [1, 2, 3]}  4

In [3]:
dict_columns_to_columns(df, cols=['a', 'b'], is_multiindex=False)

        a_a1       a_a2       b_b1  c
0  [1, 2, 3]  [1, 2, 3]  [1, 2, 3]  4

In [5]:
dict_columns_to_columns(df[['a', 'b']])

        a_a1       a_a2       b_b1
0  [1, 2, 3]  [1, 2, 3]  [1, 2, 3]

In [6]:
dict_columns_to_columns(df)

        a_a1       a_a2       b_b1  c
0  [1, 2, 3]  [1, 2, 3]  [1, 2, 3]  4